version: '2'
services:
  phabricator:
    build: ./
    image: phabricator/phabricator
    container_name: phabricator
    restart: unless-stopped
    volumes:
       - config:/var/www/phabricator/conf/local
       - repo:/var/repo
       - /etc/resolv.conf.docker:/etc/resolv.conf
    ports:
       - 80:80
       - 443:443
       - 22:22
    network_mode: bridge
    depends_on:
      - database
      - daemon
  daemon:
    build:
      context: ./
      dockerfile: Dockerfile.daemon
    image: phabricator/daemon
    container_name: phabricator_daemon
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - config:/var/www/phabricator/conf/local
      - repo:/var/repo
    depends_on:
      - database
  database:
    image: mariadb:latest
    container_name: phabricator_db
    volumes:
      - dbconfig:/etc/mysql
      - dbdata:/var/lib/mysql
    ports:
      - 3366:3306
    environment:
      MYSQL_ROOT_PASSWORD: waGui2avohmaiqu0
    network_mode: bridge
volumes:
  config:
    driver: local
  repo:
    driver: local
  dbconfig:
    driver: local
  dbdata:
    driver: local
