version: '2'
x-environment:
  &environment
  MYSQL_ROOT_PASSWORD: Iesu8Withahdeeg1
services:
  phabricator:
    build: ./
    image: gtgt/phabricator
    container_name: phabricator
    restart: unless-stopped
    volumes:
       - config:/var/www/phabricator/conf/local
       - repo:/var/repo
       #- /etc/resolv.conf:/etc/resolv.conf
    ports:
       - 80:80
       #- 443:443
       - 22:22
    environment:
      << : *environment
      GIT_SSL_NO_VERIFY: 1
    network_mode: bridge
    links:
      - database
  daemon:
    build:
      context: ./
      dockerfile: Dockerfile.daemon
    image: gtgt/phabricator-daemon
    container_name: phabricator_daemon
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - config:/var/www/phabricator/conf/local
      - repo:/var/repo
      #- /etc/resolv.conf:/etc/resolv.conf
    environment:
      << : *environment
      GIT_SSL_NO_VERIFY: 1
    links:
      - database
      - phabricator
  database:
    build:
      context: ./
      dockerfile: Dockerfile.database
    image: gtgt/phabricator-database
    container_name: phabricator_db
    restart: unless-stopped
    volumes:
      - dbconfig:/etc/mysql
      - dbdata:/var/lib/mysql
    ports:
      - 3366:3306
    environment:
      << : *environment
    network_mode: bridge
volumes:
  config:
    driver: local
  repo:
    driver: local
  dbconfig:
    driver: local
  dbdata:
    driver: local
